# Пожалуйста, не изменяйте версию плагина.
version: 1
lang: "en"
debug: false
main_train_material: FURNACE
coupler_material: CHAIN
coupler_selected_particle: VILLAGER_HAPPY
inventory:
  backward:
    slot: 10
    material: DIRT
    name: Backward
    lore:
      - Backward
  still:
    slot: 13
    material: REDSTONE
    name: Still
    lore:
      - Still
  forward:
    slot: 16
    material: STONE
    name: Forward
    lore:
      - Forward